### ISSUE TITLE
Add Support for Azure DevOps

### ISSUE THREAD

**Issue by tmtso** [hailstorm75/ModularDoc#237]
Azure DevOps has a different Style for displaying Mermaid Diagrams. 
It's using ::: instead of ```. 

As reference a link to the official documentation: 
https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops

Could you add a new config to your Plugin "GITMarkdown" for Azure DevOps if you have time for it?
The current workaround is to change every file after generation, but for large projects this takes a lot of time or an additional tool to search and replace the values.

Thanks

**Comment by hailstorm75** [comment]
Hello @tmtso, thanks for submitting your request. Initially I wished to support Azure DevOps; however, I could not figure out how to implement correct linking between wiki pages. Each page has a unique numeric ID and I have no idea what determines it.

I will be able to add support for AzureDevOps in one and a half months. Said support will exclude exporting to the Wiki.

**Comment by tmtso** [comment]
Hello @hailstorm75, 
thanks for your fast reply. It would be great if you can do this for the general syntax. For uploading the files to DevOps, I will find a solution. Maybe I just do this manually. But if all other things work out, that would be great. 
If I find out, how DevOps handles the ID thing, I will inform you. Without looking into this, maybe an option would be to have an config file imported, which contains the IDs for generating links. If it's possible to get the links from somewhere.

Thanks and Happy Holidays!

**Comment by tmtso** [comment]
Update regarding the Linking between Pages, if I understand you correctly, is pretty easy:
https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#supported-in-definition-of-done--markdown-widget--pull-requests--readme-files--wikis-6 -> Supported links for Wiki
I tried it myself and I just added:
`[text to display](/parent-page/child-page)` and it worked great, without the IDs.

**Comment by hailstorm75** [comment]
Thank you for the analysis, I shall tackle this task as soon as I fix the reported issues.

**Comment by hailstorm75** [comment]
@tmtso Azure DevOps support has been implemented!

**Comment by tmtso** [comment]
@hailstorm75 thanks, I will try it next week and give you feedback ;)

**Comment by tmtso** [comment]
@hailstorm75 looks great, thank you. I can't wait to see the private classes.
