### ISSUE TITLE
Add Support for private classes/methods etc

### ISSUE THREAD

**Issue by tmtso** [hailstorm75/ModularDoc#238]
I'm currently working on a project and wanted to create a wiki inside Azure DevOps for internal and external documentation.
Your tool works great for external documentation, as it's only displaying public methods.
For the internal documentation, private methods get ignored, although they are exported by Visual Studio as xml documentation. 

Could you add an option to enable specific types to be added inside the markdown files?
E.g. add an option (checkbox?) for exporting public, private, internal elements? You don't need to add options for each type (class/method etc). Or even simpler, add an option to enable private output.  

That would help a lot, thanks

**Comment by hailstorm75** [comment]
Great idea. I shall add that.

**Comment by tmtso** [comment]
Thanks for your fast reply, do you have a rough estimate, when this is usable, as this has a higher priority compared to the other issue. 
But don't stress and Happy Holidays ;)

**Comment by hailstorm75** [comment]
I cannot say, as I have my bachelor's exams next month. Once I'm done with them, I shall implement the missing feature for you.

**Comment by tmtso** [comment]
Then good luck, it's an awesome project and I'm sure you will succeed. 
And don't stress about my feature requests, just take your time ;)

**Comment by hailstorm75** [comment]
@tmtso will you be able to test the implementation with your project? It is available on the [238-add-support-for-private-types-and-members](https://github.com/hailstorm75/ModularDoc/tree/238-add-support-for-private-types-and-members) branch

**Comment by tmtso** [comment]
@hailstorm75 I will try to test this next week/the week after. 
Thanks for your effort ;)

**Comment by tmtso** [comment]
@hailstorm75 it looks great. I see all private/protected member of my code, except for private properties. These are not visible. 
I don't know if this is intended or not, but that's the only thing I found, while testing a few classes.
![image](https://user-images.githubusercontent.com/27405540/226580877-8239e131-767f-4aae-a8b1-922823bed0ff.png)
Here is a screenshot from inside DevOps, where the private properties from the screenshot above are not visible:
![image](https://user-images.githubusercontent.com/27405540/226581435-19bd95e6-3479-4d61-a2fd-d336d06dd520.png)

If you want me to test another iteration, just tell me.

Thanks again for this amazing work

**Comment by hailstorm75** [comment]
Ah, you mean fields. I shall extend the tool to include them too

**Comment by hailstorm75** [comment]
@tmtso It should now include type fields and private properties

**Comment by tmtso** [comment]
@hailstorm75 it looks and works great, thanks for the awesome work!
As soon, as it's in the release branch, you can/I will close the ticket.
